baseURL: "https://angelcontractingandrenovations.ca/"
theme: "blakeflood.github.io"
languageCode: "en-us"
themesDir: "../.."
title: "Angel Contracting and Renovations"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Angel Contracting and Renovations"
  description: "We specialize in providing services to desing websites, applications, build and maintain business for customers."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "50 St George St, Toronto, ON"

  contact:
    - "johnathan627@hotmail.com"
    - "207.555.0119"

  copyright: "All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/"
      weight: 1

    - name: "Services"
      url: "/services"
      weight: 2

    - name: "About us"
      url: "/about"
      weight: 3
    
    - name: "Rebates"
      url: "/rebates"
      weight: 4

  buttons:
    - name: "Book a call"
      url: "https://docs.google.com/forms/d/e/1FAIpQLSdQLrs_6yYdZHQBbZXNw-Th4sLCJ2S3Cv-t7W2T-UeJ0KKGGg/formResponse"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/"
      weight: 1

    - name: "Services"
      url: "/services"
      weight: 2

    - name: "About us"
      url: "/about"
      weight: 3

taxonomies:
  series: "series"
  tags: "tags"
